language: csharp
solution: ./Backend/SppdDocs.sln
mono: none
dotnet: 2.1.403

script:
- cd Backend
- dotnet restore
- dotnet build
- dotnet test tests/SppdDocs.Core.Tests.Unit/SppdDocs.Core.Tests.Unit.csproj
